### ISSUE TITLE
experiments - PACl vs. effluent

### ISSUE THREAD

**Issue by ecantlebary** [AguaClara/stars_filter_theory#14]
One unknown that we have always had in our effluent turbidity is why it never reaches 5NTU even after filter failure.  Furthermore, we don't know the difference flocs make in turbidity in comparison to individual particles. 

To improve our understanding of these processes, we will run experiments that bypass the filter in order to see the relationship between PACl dosage and effluent turbidity. 

We will run the experiments with 2, 1.55, 1.1, 0.65, 0.2, and 0 mg/L of PACl. We will run the apparatus until a steady state system is achieved, and the effluent turbidity is consistent. We can use this data to better understand the filter's effect on turbidity overall.

**Comment by dylanvucornell** [comment]
We will also perform these experiments with the constriction in place.
