### ISSUE TITLE
Red-Dye Flocs Experiment 4/11

### ISSUE THREAD

**Issue by dylanvucornell** [AguaClara/stars_filter_theory#22]
The team is planning to use the filter constriction sub-team's apparatus/camera to record videos of three different conditions:
1. Control with two different PACl dosages and red dye.
2. Red dye and two different PACl dosages with our pipette constriction.

The plan is to run these experiments Wednesday 4/11 with Jonathan and Lucinda's help. The videos and observations will be recorded in this thread.

System parameters:
Water pump - 38.6 rpm // 1.79mL/s
Dye (clay model) - 1.84 g/L stock conc, 13.3 rpm // 0.025 mL/s (exp. 1), 6.5 rpm (exp. 2)
PACl - 13.3 rpm // 0.025 mL/s, 6.5 rpm (exp. 2)

**Comment by dylanvucornell** [comment]
Finished experiments for second condition listed above with Jonathan 4/11. Jonathan has control for the first dye concentration. He will upload these videos to google drive.

**Comment by dylanvucornell** [comment]
Finished experiments 4/13. Results seem to prove that our fabricated pipette constriction was breaking apart our flocs into smaller particles. Links to the videos will be posted in this Issue once they are available.

**Comment by JonathanDavidHarris** [comment]
[4-11 experiments](https://drive.google.com/drive/u/0/folders/1yUSCdTXIk_KnMu73OcT5udK01k97Ilxa)

[4-13 experiments](https://drive.google.com/drive/u/0/folders/1Uafq4EbwZWXXICfnyv0K4FJ0bf1jsxvA)

[Filter Constrictions Control Experiemt 3-23](https://drive.google.com/file/d/125flfmdWQUzdLbNkAbIODlrEk_kotEMs/view?usp=sharing)
