### ISSUE TITLE
High G Flocculation Experiments

### ISSUE THREAD

**Issue by dylanvucornell** [AguaClara/stars_filter_theory#24]
Purpose: 
To examine the effects of high G flocculation on filter performance.

Theory: 
It is hypothesized that the particles that escape the filter are the primary particles that slip past flocculation. This is due to the hypothesized effect that when particles aggregate into larger flocs, it becomes harder for these larger flocs to continue aggregating with primary particles much smaller than their size (due to shear force and other factors). These primary particles then bypass the filter and exit with the cleaned water. We believe that high G flocculation will produce a more uniform distribution of smaller flocs, as the high velocity gradient will discourage larger flocs from forming. These smaller flocs will be able to flocculate with isolated primary particles during the flocculation pocess due to the more forgiving size different of the flocs to the primary particles. Further, it has been found that in slow-flocculation, PACl particles tend to stick to flocculator walls, decreasing the expected dosage; in contrast, high G flocculation has been found to fix this problem, resolving the expected PACl dosage (and effectively increasing the PACl dosage from what has been previously observed by the team). This should increase the PACl coverage on the clay particles, making them flocculate and entrain better in the filter.

Experiment:
1. Implement the high G flocculation (described in a comment below from meeting update) before the filter. Run filter experiment with various PACl dosages.
2. Implement the high G flocculation before the filter and add the slow-flocculator (current winding flocculator used by the team) between the high G flocculator and filter. Run filter experiment with various PACl dosages TBD. The purpose of this experiment is just to further test the idea of floc size effecting the filter performance/failure time, given that no particles escape the flocculator (see theory).

**Comment by dylanvucornell** [comment]
We meet regularly:
Monday 6:30-7:30
Tuesday 12:00-2:00
Wednesday 4:30-7:00 (although, we have a meeting with filter constriction 4/11 when we come back)
Friday 4:30-6:30
@TanviNaidu @Roswell-Lo

**Comment by TanviNaidu** [comment]
Hi guys,
I can meet with you during the Monday slot, latter half of Tuesday, and Friday slot!

**Comment by Roswell-Lo** [comment]
Monday and Friday work for me in general.  Wednesday is usually good but taking the FE exam on 4/11.

**Comment by dylanvucornell** [comment]
Hey, Tanvi if you can make the Monday slot that'd be great! If not, Friday works for all of us it seems.

**Comment by TanviNaidu** [comment]
I can do Friday at 4:30!

**Comment by dylanvucornell** [comment]
https://drive.google.com/file/d/0B0pBGQlo3PAZQmlHRFhHeXNlNXM/view?ts=5ad52a8a

The High G flocculation team suggested that we vary flow rate in order to change the G value. Fabrication of a new flocculator may be necessary in order to correspond with the G value calculations. Above is a mathcad file where we can insert our parameters in oder to get a given G value. It was suggested that we aim to create a flocculator with a constant around 100 G. They also suggest we vary the G value and see how that affects the filter.
