### ISSUE TITLE
Effluent Turbidity does not reach 5 NTU

### ISSUE THREAD

**Issue by ecantlebary** [AguaClara/stars_filter_theory#8]
[28-02-17 2 mgL control.xlsx](https://github.com/AguaClara/stars_filter_theory/files/1791268/28-02-17.2.mgL.control.xlsx)

Even when the experiment is run past failure time, the effluent NTU doesn't reach 5NTU. One possibility is that the size of the particles impacts the measured turbidity, so when the particles are larger, the NTU is lower.  This will be examined after running the orifice experiment.

**Comment by dylanvucornell** [comment]
Work in progress with new experiment - see Experiment PACl vs. Effluent
